model_name: 'lstm'

seed: 42
train_mode: 'sim'
test_mode: 'exp'
train_sample: [1, 3, 4, 5, 6]
test_sample: [1, 2, 3, 7]
n_epochs: 50
lr: 1.e-4
val_step: 100
save_step: 100
normalize: 'minmax'
save_all: True
optimizer_type: 'adam'
learning_type: 'grad'

# common model parameters
input_dim: 16
hidden_dim: 32
dropout: 0.0
num_seg: 1

mmd_weight: 0.1
dan_weight: 0.1     # 0.8 vis feas